version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    ports:
      - 8080:8080
      - 9229:9229
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - myredis
  myredis:
    container_name: myredis
    image: redis:6
    networks:
      - webnet
networks:
  webnet:
